### ISSUE TITLE
Firefox版的扩展功能比Chrome版可供选择的词典少好多

### ISSUE THREAD

**Issue by McGiRG3z** [ninja33/ODH#76]
Firefox版本可供选择的词典，只有几个汉英词典，没有英英词典，也没有小语种词典，希望能支持Chrome版本同等数量的词典。

另外，请问如果选择“英汉“词典，在扩展中设置为“单语”，可不可以在制作Anki卡片的时候，也只生成英文的例句，不要中文翻译。

**Comment by ninja33** [comment]
Firefox目前不支持动态加载脚本，所以把不常用的脚本隐藏了。因为如果有问题，除了发布新版本外，没办法及时修复，不像Chrome动态更新一下脚本就好了。小语种和其他的不常用脚本没那么多精力维护。

至于你讲的英英词典，随插件发布的基本都是英汉的，但是后台选项设成单语，显示出来的就是英英。至于你说anki制卡后显示也要英英，那个需要模板配合。在模板的style样式区域，输入下面的css样式，就可以不显示中文了。

```css
.chn_tran{
  display:none; 
}

.chn_sent{
  display:none; 
}
```
